config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pokemon#index"

  get "/about", to: "application#about"

  resources :pokemon, only: [:index, :show]

  resources :types, only: [:index, :show]

  resources :moves, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/move.rb
class Move < ApplicationRecord
  has_and_belongs_to_many :pokemons

  validates :name, presence: true

  scope :search, -> (query) { where('name LIKE ?', "%#{query}%")}
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_and_belongs_to_many :types
  has_and_belongs_to_many :moves

  has_one_attached :image

  validates :name, presence: true
  validates :height, numericality: { greater_than: 0 }
  validates :weight, numericality: { greater_than: 0 }

  scope :search, -> (query) { where('name LIKE ?', "%#{query}%")}
end

app/models/type.rb
class Type < ApplicationRecord
  has_and_belongs_to_many :pokemons

  validates :name, presence: true

  scope :search, -> (query) { where('name LIKE ?', "%#{query}%")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def about
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def index
    if params[:search]
      @moves = Move.search(params[:search]).page(params[:page]).per(30)
    else
      @moves = Move.page(params[:page]).per(30)
    end
  end

  def show
    @move = Move.find(params[:id])
  end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  def index
    if params[:search]
      @pokemons = Pokemon.search(params[:search]).page(params[:page]).per(30)
    else
      @pokemons = Pokemon.page(params[:page]).per(30)
    end
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end



  #TODO: limit parameters

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    if params[:search]
      @types = Type.search(params[:search]).page(params[:page]).per(30)
    else
      @types = Type.page(params[:page]).per(30)
    end
  end

  def show
    @type = Type.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/application/about.html.erb
<div class="flex flex-col items-center">
     <h1 class="font-bold my-4 text-2xl">Dataset Description and ERD</h1>

     <p class="mb-10">I am pulling data from the <a href="https://pokeapi.co/api/v2/">Poke Api V2</a> using the Poke-api-v2 <a href="#https://github.com/rdavid1099/poke-api-v2">gem</a>. I am grabbing specifically the Pokemon's Name, height, weight, types, and potential moves. Will have three tables Types, Pokemon, and Moves, each having a names column with pokemon also having weight and height.</p>

     <%= image_tag 'erd.jpg', alt: 'an Entity Relationship Diagram'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="bg-slate-400 flex justify-between px-20 sticky top-0 text-3xl">
      <%= link_to "Pokemon", root_path%>
      <%= link_to "Types", types_path%>
      <%= link_to "Moves", moves_path%>
      <%= link_to "About", about_path%>
    </nav>
    <main class="container mx-auto mt-2 px-5 flex-col items-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/moves/index.html.erb
<div class="grid grid-cols-6 gap-4 mx-auto">
     <%= form_with url: moves_path, method: :get, local: true, class: "col-span-6 bg-purple-600 flex items-center justify-between" do%>
          <%= label_tag :search, "Search for Moves"%>
          <div>
                    <%= text_field_tag :search, params[:search]%>
                    <%= submit_tag "Search", class: "bg-blue-300" %>
               </div>
     <%end%>

     <% @moves.each do | move | %>
          <div class="p-3 bg-gray-400">
               <H2><%= link_to move.name, move_path(move)%></H2>
          </div>
     <%end%>
</div>

<%= paginate @moves %>

app/views/moves/show.html.erb
<div class="flex flex-col items-center mx-auto">
     <h1 class="mb-5 font-bold text-2xl"><%= @move.name%></h1>

     <h2 class="my-5 font-bold text-xl">Pokemon that can learn</h2>
     <div class="grid grid-cols-6 gap-4 mx-auto">
          <% @move.pokemons.each do |pokemon| %>
               <div class="p-3 bg-gray-400">
                    <p><%= link_to pokemon.name, pokemon_path(pokemon) %></p>
               </div>
          <% end %>
     </div>
</div>

app/views/pokemon/index.html.erb
<div class="grid grid-cols-6 gap-4 mx-auto">
     <%= form_with url: pokemon_index_path, method: :get, local: true, class: "bg-purple-600 col-span-6 flex items-center justify-between" do%>
               <%= label_tag :search, "Search for Pokemon"%>
               <div>
                    <%= text_field_tag :search, params[:search]%>
                    <%= submit_tag "Search", class: "bg-blue-300" %>
               </div>
     <%end%>
     <% @pokemons.each do | pokemon | %>
          <div class="p-3 bg-gray-400">
               <H2><%= link_to pokemon.name, pokemon_path(pokemon)%></H2>
               <p>height:
                    <% if pokemon.height > 9%>
                         <%=pokemon.height / 10%> M
                    <% else %>
                         <%=pokemon.height * 10%> Cm
                    <% end %>
               </p>
               <p>weight: <%= pokemon.weight / 10%> Kg</p>
               <% pokemon.types.each do |type| %>
                    <p><%= link_to type.name, type_path(type) %></p>
               <%end%>
          </div>
     <%end%>
</div>

<%= paginate @pokemons %>

app/views/pokemon/show.html.erb
<div class="flex flex-col items-center mx-auto">
     <h1 class="mb-5 font-bold text-2xl"><%= @pokemon.name%></h1>

     <p>
          height:
          <% if @pokemon.height > 9%>
               <%=@pokemon.height / 10%> M
          <% else %>
               <%=@pokemon.height * 10%> Cm
          <% end %>
     </p>
     <p>weight: <%= @pokemon.weight / 10%> Kg</p>

     <% if @pokemon.image.attached? %>
          <%= image_tag @pokemon.image %>
     <% end %>

     <h2 class="my-5 font-bold text-xl">Types</h2>
     <div class="grid grid-cols-6 gap-4 mx-auto">
          <% @pokemon.types.each do |type| %>
               <div class="p-3 bg-gray-400">
                    <p><%= link_to type.name, type_path(type) %></p>
               </div>
          <% end %>
     </div>

     <h2 class="my-5 font-bold text-xl">learnable moves</h2>
     <div class="grid grid-cols-6 gap-4 mx-auto">
          <% @pokemon.moves.each do |move| %>
               <div class="p-3 bg-gray-400">
                    <p><%= link_to move.name, move_path(move) %></p>
               </div>
          <% end %>
     </div>
</div>

app/views/types/index.html.erb
<div class="grid grid-cols-6 gap-4 mx-auto">
     <%= form_with url: types_path, method: :get, local: true, class: "col-span-6 bg-purple-600 flex items-center justify-between" do%>
          <%= label_tag :search, "Search for Types"%>
          <div>
               <%= text_field_tag :search, params[:search]%>
               <%= submit_tag "Search", class: "bg-blue-300" %>
          </div>
     <%end%>

     <% @types.each do | type | %>
          <div class="p-3 bg-gray-400">
               <H2><%= link_to type.name, type_path(type)%></H2>
          </div>
     <%end%>
</div>

<%= paginate @types %>

app/views/types/show.html.erb
<div class="flex flex-col items-center mx-auto">
     <h1 class="mb-5 font-bold text-2xl"><%= @type.name%></h1>

     <h2 class="my-5 font-bold text-xl">Pokemon</h2>
     <div class="grid grid-cols-6 gap-4 mx-auto">
          <% @type.pokemons.each do |pokemon| %>
               <div class="p-3 bg-gray-400">
                    <p><%= link_to pokemon.name, pokemon_path(pokemon) %></p>
               </div>
          <% end %>
     </div>
</div>